# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name_plural': '单选题的选项'},
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Questionnaire', verbose_name='关联问卷'),
        ),
    ]
